[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run build",
    "mkdir -p .next/standalone/public",
    "mkdir -p .next/standalone/.next/static",
    "cp -r public/* .next/standalone/public/",
    "cp -r .next/static/* .next/standalone/.next/static/"
]

[start]
cmd = "node .next/standalone/server.js"

[variables]
HOSTNAME = "0.0.0.0"
